---
title: "Rapport"
author: "Inspecteur Gadget"
date: "2023-05-15"
output:
  prettydoc::html_pretty:
    theme: hpstr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(usmap)
library(gridExtra)
```

```{r data, include=FALSE}
data <- read_csv("../data/census-income.csv")
```


```
*Faire ici une introduction ; cf readme?*
```


# Répartition par âge

```
Voici la répartition par âge de notre échantillon.
```

```{r income, echo=FALSE}
ggplot(data, aes(x = age)) +
    geom_histogram(binwidth = 5) +
    labs(title = "Age distribution", x = "Age", y = "Count")
```

```
On remarque ainsi que la majeure partie de l'échantillon a moins de 45 ans. Il existe néanmoins de fortes disparités ; l'engagement des Etats-Unis dans la guerre du Vietnam, notamment à partir de 1965 explique en partie ces écarts démographiques. Les classes d'âge qui se sont majoritairement enrolés au Vietnam ont entre 40 et 50  au moment de l'enquête, et on peut constater leur sous-représenatation dans la population générale. En mobilisant plus de 2 millions de soldats, dont la moyenne d'âge était de 19 ans, la guerre a en effet fait un peu moins de 60 000 morts du côté américain.
Un déficit des naissances est aussi observé pour les classes d'âges allant de 12 à 30 ans, avec un pic vers 20 ans ; ce sont des naissances "manquantes", qui n'ont pas eu lieu à cause de l'absence des hommes enrolés dans la guerre.

```

# Pays de naissance

```
On s'intéresse désormais aux pays de naissance des personnes interrogées dans notre échantillon.
```
```{r income, echo=FALSE}
ggplot(data, aes(y = country_of_birth_self)) +
    geom_bar() +
    labs(x = "Count", y = "Country of Birth")
```

```
On constate que l'écrasante majorité de la population interrogée est née aux Etats-Unis. 

*Intégrer ici un bar chart naissance USA vs naissance ailleurs, pour déduire un pourcentage et comparer éventuellement à d'autrs pays ou à maintenant*

Il convient aussi de souligner qu'un pays de naissance n'est pas toujours révélateur d'une nationalité. Un enfant américain peut très bien naître sur le sol français par exemple. Néanmoins cet indicateur peut être utile pour modéliser les mobilités de population et l'attraction des Etats-Unis sur la scène internationale. Il est un indicateur complémentaire de la nationalité, qui elle aussi peut-être variable (elle peut s'acquérir par exemple, après un certains nombres d'années de résidence).
Quelques pays comme le Mexique semblent néanmoins se distinguer, mais il est néanmoins difficile de faire une analyse. 
 Pour mieux appréhender la pluralité des pays d'origine de ces immigrés, voici donc un autre graphique, qui exclut cette fois-ci les Etats-Unis.
```


# Pays de naissance - Hors Etats-Unis

```{r income, echo=FALSE}
world <- data %>%
    filter(country_of_birth_self != "United-States")

ggplot(world, aes(y = country_of_birth_self)) +
    geom_bar() +
    labs(x = "Count", y = "Country of Birth")
```
```
On a cette fois-ci une vision plus claire des pays de naissance
```


# Income level by race

```{r level, echo=FALSE}
ggplot(data, aes(x = income_level, fill = race)) +
    geom_bar(position = "fill") +
    labs(
        title = "Income level by race",
        x = "Income Level", y = "Percentage", fill = "Race"
    )
```
